"""Génération Gerber RS-274X — couches cuivre + edge cuts (section 6.6).

Format minimal valide : header de format (%FSLAX36Y36*%), unités mm
(%MOMM*%), définition d'apertures circulaires par largeur de piste, tracés
D01/D02, pastilles flashées D03. Conçu pour être relisible par les visionneuses
Gerber standard (gerbv, KiCad GerbView).
"""

from __future__ import annotations

import math
from typing import Dict, List, Tuple

from common.design_model import Board, Segment

_FMT_HEADER = (
    "%FSLAX36Y36*%\n"   # format 3.6 — coordonnées en µm implicites
    "%MOMM*%\n"          # unités métriques
    "%ADD10C,0.200*%\n"  # aperture 10 : piste standard 0,2 mm
    "%ADD11C,0.400*%\n"  # aperture 11 : piste puissance 0,4 mm
    "%ADD12C,0.300*%\n"  # aperture 12 : via 0,3 mm
    "%ADD13C,0.600*%\n"  # aperture 13 : pastille standard 0,6 mm
)
_APERTURE = {0.2: "10", 0.4: "11", 0.3: "12", 0.6: "13"}


def _coord(value_mm: float) -> str:
    """Coordonnée RS-274X : entier 3.6 (µm), sans point décimal."""
    return f"{int(round(value_mm * 1e6)):06d}"


def _aperture_for(width_mm: float) -> str:
    widths = sorted(_APERTURE)
    best = min(widths, key=lambda w: abs(w - width_mm))
    return _APERTURE[best]


def render_copper_layer(board: Board, layer_index: int) -> str:
    """RS-274X d'une couche cuivre : segments + vias + pastilles de la couche."""
    lines: List[str] = ["*RS274X generated by pcb_ai_designer_v2/exporter*"]
    lines.append(_FMT_HEADER)
    lines.append("G01*")  # interpolation linéaire

    current_aperture = None
    for net in board.nets.values():
        for seg in net.routed_segments:
            if seg.layer != layer_index:
                continue
            ap = _aperture_for(seg.width_mm)  # via 0,3 mm → aperture 12 via la table
            if ap != current_aperture:
                lines.append(f"D{ap}*")
                current_aperture = ap
            x1, y1 = _coord(seg.x1_mm), _coord(seg.y1_mm)
            x2, y2 = _coord(seg.x2_mm), _coord(seg.y2_mm)
            if seg.is_via:
                # via : flash d'une pastille circulaire
                lines.append(f"X{x1}Y{y1}D03*")
            else:
                lines.append(f"X{x1}Y{y1}D02*")
                lines.append(f"X{x2}Y{y2}D01*")

    # pastilles des composants présents sur cette couche (aperture 13 : 0,6 mm)
    pad_ap = _APERTURE[0.6]
    lines.append(f"D{pad_ap}*")
    for ref, comp in board.components.items():
        placement = board.placements.get(ref)
        if placement is None or placement.layer != layer_index:
            continue
        for pad in comp.pads:
            lines.append(f"X{_coord(pad.x_mm)}Y{_coord(pad.y_mm)}D03*")

    lines.append("M02*")  # fin de fichier
    return "\n".join(lines)


def render_edge_cuts(board: Board) -> str:
    """Contour de la carte (couche Edge.Cuts) : rectangle aux dimensions réelles."""
    w, h = board.width_mm, board.height_mm
    corners: List[Tuple[float, float]] = [(0, 0), (w, 0), (w, h), (0, h), (0, 0)]
    lines = ["*RS274X edge cuts — pcb_ai_designer_v2*", _FMT_HEADER, "G01*", "D10*"]
    prev = corners[0]
    lines.append(f"X{_coord(prev[0])}Y{_coord(prev[1])}D02*")
    for corner in corners[1:]:
        lines.append(f"X{_coord(corner[0])}Y{_coord(corner[1])}D01*")
    lines.append("M02*")
    return "\n".join(lines)


def layer_filename(layer_index: int, layer_count: int) -> str:
    """Nom de fichier conventionnel : F_Cu.gbr, In1_Cu.gbr..., B_Cu.gbr."""
    if layer_index == 0:
        return "F_Cu.gbr"
    if layer_index == layer_count - 1:
        return "B_Cu.gbr"
    return f"In{layer_index}_Cu.gbr"


def export_gerbers(board: Board) -> Dict[str, str]:
    """Exporte toutes les couches cuivre + edge cuts → {filename: contenu}."""
    out: Dict[str, str] = {}
    copper_layers = [l.index for l in board.layers if l.is_copper]
    for layer_index in copper_layers:
        out[layer_filename(layer_index, len(copper_layers))] = render_copper_layer(board, layer_index)
    out["Edge_Cuts.gbr"] = render_edge_cuts(board)
    return out
